markdown: kramdown

title: KT's scribbles

url: "https://dracarys983.github.io"
baseurl: "/scribbles"

plugins:
    - jekyll-paginate

whitelist:
    - jekyll-paginate

permalink: /:year/:month/:day/:title
paginate: 5
paginate_path: /page:num/

theme: jekyll-theme-minimal
